/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Login
         * @description Redirect to Cognito's managed sign-in page, then back to `next` (an app route).
         */
        get: operations["auth_login_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Callback
         * @description Exchange the code, validate the ID token and start the session.
         */
        get: operations["auth_callback_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Logout
         * @description Clear the session, then end the Cognito session too.
         */
        get: operations["auth_logout_auth_logout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Me
         * @description The current user, or a 401 in cognito mode without a session.
         */
        get: operations["auth_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check for the uptime monitor. Depends on nothing external.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Analysis
         * @description Starts the agent in the background and returns a Job ID immediately.
         */
        post: operations["start_analysis_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Polled by the frontend to check progress.
         *
         *     `state` is the job's lifecycle state and `progress` its latest message;
         *     `history` replays every message so far. `error` is set once the job has
         *     failed or been interrupted. Another user's job is a 404.
         */
        get: operations["get_status_status__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/result/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Result
         * @description Retrieves the final detailed report.
         *
         *     A stored result that no longer fits ProtocolResult (its shape changed after
         *     the job ran) is returned as stored; the frontend decides whether it can
         *     render it. Another user's job is a 404.
         */
        get: operations["get_result_result__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trace/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trace
         * @description The job's trace (#77): each LLM call's reasoning summary, output, tokens,
         *     time and estimated cost, and each stage's time. Kept out of the report so
         *     /result stays small. null for a job with no trace: one that ran before
         *     traces existed, or is still running. Another user's job is a 404.
         */
        get: operations["get_trace_trace__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description The current user's jobs, newest first (My Jobs).
         */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Job
         * @description Hard-delete one of the user's finished, failed or interrupted jobs. Another
         *     user's job is a 404; a queued or running one is a 409, since jobs can't be
         *     cancelled (#49).
         */
        delete: operations["delete_job_jobs__job_id__delete"];
        options?: never;
        head?: never;
        /**
         * Rename Job
         * @description Rename one of the user's jobs, running or not. A blank name clears it, so
         *     My Jobs shows the input summary again. Another user's job is a 404.
         */
        patch: operations["rename_job_jobs__job_id__patch"];
        trace?: never;
    };
    "/jobs/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Jobs
         * @description Delete several of the user's jobs. Running jobs and ones that aren't the
         *     user's are skipped and listed with the reason, rather than failing the rest.
         */
        post: operations["delete_jobs_jobs_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BufferStep
         * @description A buffer step in the report: what the model extracted, and where it sits.
         */
        BufferStep: {
            /**
             * Purification Step
             * @description A highly specific name for the purification step. Combine the exact technique or resin name from the text with the action (e.g., Lysis, Wash, Elution). Examples: 'Ni-NTA Affinity Chromatography - Wash', 'Cell Extraction'.
             */
            purification_step: string | null;
            /**
             * Buffer Name
             * @description The specific name given to the buffer in the text, if any (e.g., 'Buffer A', 'Lysis Buffer').
             */
            buffer_name?: string | null;
            /**
             * Buffer Composition
             * @description List buffering agents and their concentrations (e.g., '50 mM Tris', '20 mM HEPES'). If not specified, leave as null.
             */
            buffer_composition?: string | null;
            /**
             * Ph
             * @description The pH of the buffer, as a number (e.g., 8.0). If not mentioned, leave as null.
             */
            ph?: number | null;
            /**
             * Salt Type
             * @description List ALL salts with their concentrations as the text states them, for example '300 mM NaCl, 5 mM MgCl2'. Give a salt's name alone only when the text gives no concentration for it.
             */
            salt_type?: string | null;
            /**
             * Buffer Supplement
             * @description List additives present in the buffer like reducing agents (DTT), nucleotides (ATP), detergents, or cryoprotectants (glycerol). For example: '2 mM DTT, 30mM imidazole'.
             */
            buffer_supplement?: string | null;
            /** Step Number */
            step_number?: number | null;
        };
        /** BulkDeleteRequest */
        BulkDeleteRequest: {
            /** Ids */
            ids: string[];
        };
        /** BulkDeleteResult */
        BulkDeleteResult: {
            /** Deleted */
            deleted: string[];
            /** Skipped */
            skipped: components["schemas"]["SkippedJob"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Hit
         * @description One BLAST hit against pdbaa, ranked and then followed to its paper.
         */
        Hit: {
            /** Protein Name */
            protein_name: string;
            /** Pdb Id */
            pdb_id: string;
            /** Length */
            length: number;
            /** E Value */
            e_value: number;
            /** Pident */
            pident: number;
            /** Query Coverage */
            query_coverage: number;
            /** Query Start */
            query_start: number;
            /** Query End */
            query_end: number;
            /** Subject Start */
            subject_start: number;
            /** Subject End */
            subject_end: number;
            /** Similarity Score */
            similarity_score?: number | null;
            /** Uniprot Id */
            uniprot_id?: string | null;
            /** Organism Name */
            organism_name?: string | null;
            /** Taxonomy Id */
            taxonomy_id?: number | null;
            /** @default Not Analyzed */
            status?: components["schemas"]["HitStatus"];
            /** Pmid */
            pmid?: string | null;
        };
        /**
         * HitStatus
         * @description Where a hit's search for a protocol ended. The value is also its display
         *     label, so this is the one place a status is worded. The frontend matches
         *     some of them exactly (BlastResults.getStatusIcon).
         * @enum {string}
         */
        HitStatus: "Not Analyzed" | "No RCSB Metadata" | "Citation Lookup Failed" | "No PMC Primary Citation" | "Paper Already Found" | "No Open Access" | "PMC Retrieval Failed" | "No Protocol Found in Paper" | "Protocol Found" | "Error Processing";
        /**
         * JobListItem
         * @description One row of GET /jobs (My Jobs).
         */
        JobListItem: {
            /** Id */
            id: string;
            /**
             * Name
             * @description The owner's name for the job, if set
             */
            name?: string | null;
            /**
             * Input Summary
             * @description The protein name, ID or FASTA header
             */
            input_summary: string;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "completed" | "failed" | "interrupted";
            /** Progress */
            progress?: string | null;
            /** Error */
            error?: string | null;
            /** Created At */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Runtime Seconds
             * @description Start to finish, or start to now while running
             */
            runtime_seconds?: number | null;
        };
        /**
         * MethodsSource
         * @description Which text the extraction agent found a paper's purification text in (#29).
         * @enum {string}
         */
        MethodsSource: "sections" | "full_text";
        /**
         * Paper
         * @description A hit's primary citation, from RCSB, and what the pipeline could read of it.
         */
        Paper: {
            /** Pmid */
            pmid: string;
            /** Pmcid */
            pmcid?: string | null;
            /** Doi */
            doi?: string | null;
            /** Title */
            title?: string | null;
            /** Journal */
            journal?: string | null;
            /** Year */
            year?: number | null;
            /** Abstract */
            abstract?: string | null;
            access?: components["schemas"]["PaperAccess"] | null;
            methods_source?: components["schemas"]["MethodsSource"] | null;
            /**
             * For Manual Review
             * @description A paper the pipeline couldn't read because it isn't open access, listed
             *     with its title, abstract and link so the user can read it (#47).
             */
            readonly for_manual_review: boolean;
            /**
             * Link
             * @description The PMC page, else the DOI, else PubMed.
             */
            readonly link: string;
        };
        /**
         * PaperAccess
         * @description How much of a paper the pipeline could read. Unset until checked.
         * @enum {string}
         */
        PaperAccess: "open" | "pmc_restricted" | "not_in_pmc" | "fetch_failed";
        /**
         * ProtocolResult
         * @description A job's report, as stored and as /result serves it. Stored reports are never
         *     migrated, so fields added later are optional; see "Changing the
         *     report" in docs/system_runbooks/backend.md.
         */
        ProtocolResult: {
            /** Purifications */
            purifications?: components["schemas"]["SourceProtocol"][] | null;
            /** Comprehensive Protocol */
            comprehensive_protocol?: string | null;
            /** Raw Plan */
            raw_plan?: string | null;
            /** Blast Results */
            blast_results?: components["schemas"]["Hit"][] | null;
            /** Papers */
            papers?: components["schemas"]["Paper"][] | null;
            /** Error Message */
            error_message?: string | null;
            /** Synthesis Skipped */
            synthesis_skipped?: string | null;
        };
        /** PurificationRequest */
        PurificationRequest: {
            /**
             * Fasta Id
             * @description Protein FASTA sequence or ID
             */
            fasta_id: string;
            /**
             * Failed Purification Text
             * @description User-provided failed purification text to override CTTdb lookup
             */
            failed_purification_text?: string | null;
            /**
             * Min Percent Identity
             * @default 90
             */
            min_percent_identity?: number;
            /**
             * Min Query Coverage
             * @default 90
             */
            min_query_coverage?: number;
            /**
             * Max Evalue
             * @default 0.00001
             */
            max_evalue?: number;
            /**
             * Max Hits
             * @default 10
             */
            max_hits?: number;
            /**
             * Max Protocols
             * @description Source protocols to extract before the literature search stops
             * @default 3
             */
            max_protocols?: number;
        };
        /** RenameJobRequest */
        RenameJobRequest: {
            /** Name */
            name?: string | null;
        };
        /** SkippedJob */
        SkippedJob: {
            /** Id */
            id: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "running" | "not_found";
        };
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "paper" | "internal" | "user";
        /**
         * SourceProtocol
         * @description A protocol the planner works from: a paper's, or the failed one.
         */
        SourceProtocol: {
            /** Purification Text */
            purification_text?: string | null;
            /** Protocol */
            protocol?: components["schemas"]["BufferStep"][] | null;
            /** Article Title */
            article_title?: string | null;
            /** Article Link */
            article_link?: string | null;
            /** Organism Name */
            organism_name?: string | null;
            /** Uniprot Id */
            uniprot_id?: string | null;
            source?: components["schemas"]["SourceKind"] | null;
            /** Pdb Id */
            pdb_id?: string | null;
        };
        /** StageTime */
        StageTime: {
            /** Name */
            name: string;
            /** Seconds */
            seconds: number;
        };
        /** Trace */
        Trace: {
            /** Model */
            model?: string | null;
            /**
             * Steps
             * @default []
             */
            steps?: components["schemas"]["TraceStep"][];
            /**
             * Stages
             * @default []
             */
            stages?: components["schemas"]["StageTime"][];
            /** Total Seconds */
            readonly total_seconds: number;
            /** Input Tokens */
            readonly input_tokens: number;
            /** Output Tokens */
            readonly output_tokens: number;
            /** Reasoning Tokens */
            readonly reasoning_tokens: number;
            /**
             * Cost Usd
             * @description The estimated total, or None when any step's model has no price.
             */
            readonly cost_usd: number | null;
        };
        /**
         * TraceStep
         * @description One LLM call.
         */
        TraceStep: {
            /**
             * Agent
             * @enum {string}
             */
            agent: "extraction" | "structuring" | "planner" | "formatter";
            /** Subject */
            subject?: string | null;
            /** Source Key */
            source_key?: string | null;
            /** Model */
            model?: string | null;
            /** Reasoning */
            reasoning?: string | null;
            /** Output */
            output?: string | null;
            /** Seconds */
            seconds: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens?: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens?: number;
            /**
             * Reasoning Tokens
             * @default 0
             */
            reasoning_tokens?: number;
            /** Cost Usd */
            cost_usd?: number | null;
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_auth_login_get: {
        parameters: {
            query?: {
                next?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_callback_auth_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_logout_auth_logout_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    start_analysis_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_status__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_result__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtocolResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_trace__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trace"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListItem"][];
                };
            };
        };
    };
    delete_job_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_job_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_jobs_jobs_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
