// Mock Data for testing purposes -- set VITE_USE_MOCK in .env to true if testing
import type { ProtocolResult } from '../types/api';

export const MOCK_SUCCESS_RESULT: ProtocolResult = {
    comprehensive_protocol: `
## His-tag Purification Protocol

**Overview**: This protocol describes the purification of a His-tagged protein using Ni-NTA affinity chromatography.

1.  **Lysis**: Cell lysis in specific buffer.
2.  **Wash**: Removal of non-specific binders.
3.  **Elution**: Elution of the target protein with Imidazole.
`,
    purifications: [
        {
            purification_text: 'Lysis Buffer: 50 mM Tris, 300 mM NaCl, 10 mM Imidazole, pH 8.0',
            article_title: 'Efficient His-Tag Purification Strategies',
            article_link: 'https://doi.org/10.1234/example1',
            protein_name: 'His6-Tagged GFP',
            protocol: {
                step: 'Lysis',
                buffer_name: 'Lysis Buffer',
                buffer_composition: '50 mM Tris, 300 mM NaCl, 10 mM Imidazole',
                ph: 8.0,
                salt_type: 'NaCl',
                buffer_supplement: '1 mM PMSF, 1 mg/mL Lysozyme'
            }
        },
        {
            purification_text: 'Wash Buffer: 50 mM Tris, 300 mM NaCl, 20 mM Imidazole, pH 8.0',
            article_title: 'Efficient His-Tag Purification Strategies',
            article_link: 'https://doi.org/10.1234/example1',
            protein_name: 'His6-Tagged GFP',
            protocol: {
                step: 'Wash',
                buffer_name: 'Wash Buffer',
                buffer_composition: '50 mM Tris, 300 mM NaCl, 20 mM Imidazole',
                ph: 8.0,
                salt_type: 'NaCl',
                buffer_supplement: 'None'
            }
        },
        {
            purification_text: 'Elution Buffer: 50 mM Tris, 300 mM NaCl, 250 mM Imidazole, pH 8.0',
            article_title: 'Efficient His-Tag Purification Strategies',
            article_link: 'https://doi.org/10.1234/example1',
            protein_name: 'His6-Tagged GFP',
            protocol: {
                step: 'Elution',
                buffer_name: 'Elution Buffer',
                buffer_composition: '50 mM Tris, 300 mM NaCl, 250 mM Imidazole',
                ph: 8.0,
                salt_type: 'NaCl',
                buffer_supplement: '5% Glycerol'
            }
        }
    ],
    blast_results: [
        {
            protein_name: 'Hypothetical Protein A',
            pdb_id: '1A2B',
            pident: 98.5,
            e_value: 0.0,
            query_coverage: 100.0,
            similarity_score: 0.99,
            taxonomy_id: '562',
            query_start: 1,
            query_end: 250
        },
        {
            protein_name: 'Putative Membrane Protein',
            pdb_id: '3X4Y',
            pident: 95.2,
            e_value: 1e-150,
            query_coverage: 99.5,
            similarity_score: 0.96,
            taxonomy_id: '83333',
            query_start: 5,
            query_end: 248
        },
        {
            protein_name: 'Crystal Structure of Target Homolog',
            pdb_id: '2Z5W',
            pident: 95.0,
            e_value: 1e-145,
            query_coverage: 98.0,
            similarity_score: 0.95,
            taxonomy_id: '9606',
            query_start: 10,
            query_end: 245
        }
    ],
    raw_plan: 'Generated by Agent logic...',
    error_message: null
};
